# Generated by Django 3.2 on 2021-04-21 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reactions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reactions',
            old_name='movie_id',
            new_name='movie',
        ),
        migrations.RenameField(
            model_name='reactions',
            old_name='user_id',
            new_name='user',
        ),
    ]
