# Generated by Django 3.2 on 2021-04-26 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0008_rename_numberofpagevisits_movie_number_of_page_visits'),
        ('reactions', '0005_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='movie',
        ),
        migrations.AddField(
            model_name='comments',
            name='movie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapi.movie'),
        ),
    ]
