# Generated by Django 3.2 on 2021-04-26 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0008_rename_numberofpagevisits_movie_number_of_page_visits'),
        ('reactions', '0006_auto_20210426_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.movie'),
        ),
    ]
