# Generated by Django 3.2 on 2021-04-27 08:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapi', '0008_rename_numberofpagevisits_movie_number_of_page_visits'),
        ('reactions', '0008_alter_comments_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='comments',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='reactions',
            unique_together={('movie', 'user')},
        ),
    ]
