# Generated by Django 3.2 on 2021-04-28 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_watchlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userwatchlist',
            name='watched',
            field=models.BooleanField(default=False),
        ),
    ]
