# Generated by Django 3.2 on 2021-04-28 14:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0008_rename_numberofpagevisits_movie_number_of_page_visits'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_watchlist', '0002_alter_userwatchlist_watched'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userwatchlist',
            unique_together={('movie', 'user')},
        ),
    ]
