# Generated by Django 3.2 on 2021-05-14 10:18

from django.db import migrations
import easy_thumbnails.fields
import myapi.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieimagethumbnail',
            name='movie_full_img',
            field=easy_thumbnails.fields.ThumbnailerImageField(default='posts/default.jpg', upload_to=myapi.models.full_picture_path),
        ),
        migrations.AlterField(
            model_name='movieimagethumbnail',
            name='movie_thumbnail',
            field=easy_thumbnails.fields.ThumbnailerImageField(default='posts/default.jpg', upload_to=myapi.models.thumbnail_path),
        ),
    ]
