# Generated by Django 3.2 on 2021-05-09 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_auto_20210509_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.ManyToManyField(default=[], related_name='genres', to='myapi.MovieGenre'),
        ),
    ]
