# Generated by Django 3.2 on 2021-04-25 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0004_alter_movie_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='numberOfDislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='numberOfLikes',
            field=models.IntegerField(default=0),
        ),
    ]
