# Generated by Django 3.2 on 2021-04-25 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0005_auto_20210425_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='numberOfPageVisits',
            field=models.IntegerField(default=0),
        ),
    ]
