# Generated by Django 3.2 on 2021-04-26 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0006_movie_numberofpagevisits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='numberOfDislikes',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='numberOfLikes',
        ),
    ]
