# Generated by Django 3.2 on 2021-04-26 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0007_auto_20210426_0830'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='numberOfPageVisits',
            new_name='number_of_page_visits',
        ),
    ]
